config/routes.rb
Rails.application.routes.draw do
  get 'cars/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources(:users)
  resources(:account_activations, only: [:edit])
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :cars do
    resources :maintenance_items
  end

  post 'update_odometer' => 'cars#update_odometer'
  get 'get_update_odometer_form' => 'cars#get_update_odometer_form'
  post 'item_checked_up_on' => 'maintenance_items#item_checked_up_on'

  resources :maintenance_items, only: [:update]
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  has_many :maintenance_items, dependent: :destroy
  validates :make,
            presence: true,
            length: {
                maximum: 32
            }
  validates :model,
            presence: true,
            length: {
                maximum: 32
            }
  validates :year,
            numericality: {
                allow_blank: true,
                allow_nil: true,
                greater_than_or_equal_to: 1900,
                less_than_or_equal_to: Date.today.year + 1 # +1 to allow for models that are often set for the following year (ie. 2016 Honda Civic in September 2015)
            }
  validates :nickname,
            length: {
                maximum: 32
            }
  validates :odometer,
            presence: true,
            numericality: {
                only_integer: true,
                greater_than_or_equal_to: 0
            }

  def get_expired_maintenance_items
    return self.maintenance_items.where("due_for_checkup = 't'")
  end

  def get_display_name
    if(self.nickname != nil)
      return self.nickname
    else
      return self.year + ' ' + self.make + ' ' + self.model
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include MaintenanceItemsHelper

  before_action :logged_in_user

  def index
    @user = current_user
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @user = current_user
    @car = Car.new
  end

  def create
    @car = current_user.cars.build(car_params)
    if(@car.save)
      redirect_to @car
    else
      render 'new'
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update_attributes(car_params)
      count = update_maintenance_items()
      flash[:success] = "Update succeeded. #{count} maintenance item(s) are due for a checkup."
      redirect_to @car
    else
      render 'edit'
    end
  end

  def destroy
    Car.find(params[:id]).destroy
    flash[:success] = "Car deleted"
    redirect_to user_path(:id => current_user.id)
  end

  def get_update_odometer_form
    @car = Car.find(params[:id])
    if(@car && @car.user_id == current_user.id)

      respond_to do |format|
        format.js
      end
    end
  end

  def update_odometer
    @car = Car.find(params[:car_id])
    if(@car && @car.user_id == current_user.id && (Integer(params[:odometer]) rescue false))
      if(@car.update_attributes(:odometer => params[:odometer]))
        update_maintenance_items()
      end
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def car_params
      params.require(:car).permit(:make, :model, :year, :nickname, :description, :odometer )
    end

    def update_maintenance_items
      count = 0
      @car.maintenance_items.each do |maintenance_item|
        if(maintenance_item.interval &&
            maintenance_item.last_maintained_odometer &&
            @car.odometer > (maintenance_item.last_maintained_odometer + maintenance_item.interval))
          if(!maintenance_item.due_for_checkup)
            maintenance_item.update_due_for_checkup(true)
          end
          count = count + 1
        end
      end
      return count
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div class="car" id="car_id_<%=car.id%>">
  <div class="header clearfix">
    <%= link_to car, class: "name" do %>
        <%= car.get_display_name() %>
    <% end %>
  </div>
  <div class="odometer clearfix">
    <span class="odometer-title">Current odometer: </span>
    <span class="odometer-value"><%= car.odometer %></span>
    <span class="form-container"></span>
    <%= link_to(raw("<span class='glyphicon glyphicon-pencil edit-icon icon'></span>"), {controller: 'cars', action: 'get_update_odometer_form', id: car.id}, remote: true, class: 'update-odometer-link') %>
  </div>
  <% if car.get_expired_maintenance_items().count > 0 %>
      <div class="expired-maintenance-items-title">Maintenance items to check up on</div>
      <%= render(partial: 'maintenance_items/simple_maintenance_item', collection: car.get_expired_maintenance_items(), as: :maintenance_item) %>
  <% end %>
</div>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :make, class: 'required' %>
    <%= f.text_field :make, class: 'form-control', maxLength: 32 %>

    <%= f.label :model, class: 'required' %>
    <%= f.text_field :model, class: 'form-control', maxLength: 32 %>

    <%= f.label :year %>
    <%= f.number_field :year, class: 'form-control'%>

    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: 'form-control', maxLength: 32 %>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>

    <%= f.label :odometer, class: 'required' %>
    <%= f.number_field :odometer, class: 'form-control' %>

    <%= f.submit submitButtonText, class: "btn btn-primary" %>
<% end %>

app/views/cars/_update_odometer_form.html.erb
<%= form_tag({controller: 'cars', action: 'update_odometer'}, { method: 'post', remote: true}) do %>
    <%= hidden_field_tag(:car_id, @car.id) %>
    <%= text_field_tag(:odometer, nil, placeholder: @car.odometer) %>
    <span class="button-container">
      <span class="glyphicon glyphicon-floppy-disk save-icon icon"></span>
      <span class="glyphicon glyphicon-ban-circle cancel-changes-icon icon"></span>
    </span>
<% end %>

app/views/cars/edit.html.erb
<% provide(:title, 'Edit Car') %>
<%= link_to "Back to car", car_path(@car), class: "back-link" %>
<h1>Edit car</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render :partial => 'form', :locals => { :submitButtonText => 'Save Changes' } %>
  </div>
</div>

app/views/cars/get_update_odometer_form.js.erb
$("#car_id_<%=@car.id%>")
    .addClass("update-odometer")
    .find(".form-container")
      .append("<%=escape_javascript(render('update_odometer_form'))%>")
      .on("click", ".save-icon", function(event){
        event.preventDefault();
        $(this.closest("form")).submit();
      });

app/views/cars/index.html.erb
<% provide(:title, @user.name + " - Cars") %>

<h3>Cars (<%= @user.cars.count %>)</h3>
<% if @user.cars.any? %>
  <div class="cars">
    <%= render @user.cars %>
  </div>
<% end %>

app/views/cars/new.html.erb
<% provide(:title, 'New Car') %>
<%= link_to "Back to cars", user_path(@user), class: "back-link" %>
<h1>Add a new car</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render :partial => 'form', :locals => { :submitButtonText => 'Add Car' } %>
  </div>
</div>

app/views/cars/show.html.erb
<%= provide(:title, @car.nickname) %>
<%= provide(:class, "show-car") %>
<%= link_to "Back to all cars", user_path(@car.user), class: "back-link" %>
<div class="explanation">
  See information about your car here, including the maintenance items for the car.
  If you want to add a maintenance item, click the + button.
</div>
<h3>Car</h3>
<div class="car">
  <div class="header clearfix">
    <span class="name"><%= @car.year %> <%= @car.make %> <%= @car.model %></span>
    <% if current_user.admin? || current_user?(@car.user) %>
        <%= link_to raw("<span class='glyphicon glyphicon-pencil edit-icon icon'></span>"), edit_car_path(@car) %>
        <%= link_to raw("<span class='glyphicon glyphicon-trash delete-icon icon'></span>"), @car, method: :delete, data: { confirm: "You sure?" }  %>
    <% end %>
  </div>

  <% if !@car.nickname.empty? %>
    <div class="nickname">aka <%= @car.nickname %></div>
  <% end %>

  <% if !@car.description.empty? %>
    <span class="description"><%= @car.description %></span>
  <% end %>

  <div class="odometer">Current odometer: <%= @car.odometer %></div>
</div><h3>Maintenance Items (<%= @car.maintenance_items.count %>) <%= link_to raw("<span class='glyphicon glyphicon-plus icon-add icon'></span>"), new_car_maintenance_item_path(@car) %></h3>
  <div class="maintenance-items">
  <% if @car.maintenance_items.any? %>
        <%= render(partial: 'maintenance_items/maintenance_item', collection: @car.maintenance_items ) %>
  <% end %>
</div>

app/views/cars/update_odometer.js.erb
<%if(@car.errors.count <= 0)%>
  $("#car_id_<%=@car.id%>").replaceWith("<%=escape_javascript(render @car)%>");
  toastr.success("Odometer for <%=@car.get_display_name()%> has been updated to <%=@car.odometer %>.");

  <%if(@car.get_expired_maintenance_items().count > 0)%>
    toastr.warning("<%=@car.get_display_name()%> has <%=@car.get_expired_maintenance_items.count()%> maintenance item(s) that need servicing.");
  <%end%>
<%else%>
  <%@car.errors.full_messages.each do |msg| %>
    toastr.error("<%=msg%>");
  <%end%>
<%end%>